wechat:
  token: "0ADCEAF6CCE07DF3"
dtk:
  appKey: 5e6c5505bb8eb
  appSecret: bee6c934e19eeb5d03462b413f57187a
  dataokeToken: 0ADCEAF6CCE07DF3
  pid: mm_47344560_1373500358_110108500483
  #高效转链
  getPrivilegeLink: https://openapi.dataoke.com/api/tb-service/get-privilege-link
  #获取商品详情
  details: https://openapi.dataoke.com/api/goods/get-goods-details
  #京东商品转链
  jdItemConvert: https://openapi.dataoke.com/api/dels/jd/kit/promotion-union-convert
  #淘口令转淘口令
  tklConvert: https://openapi.dataoke.com/api/tb-service/twd-to-twd
jd:
  appKey: f18076bf3df77f0a45bd90b11d934b44
  appSecret: 4120a10bb75444c2998b0b5f1d7facab
  routerUrl: https://router.jd.com/api
  unionId: 1002425367
  #根据skuid查询商品信息
  unionGoodsItemUrl: jd.union.open.goods.promotiongoodsinfo.query
  unionConvertUrl: jd.union.open.promotion.bysubunionid.get
pdd:
  appKey: 50f12321d152448f8dab9b4456269d3b
  appSecret: 05b5f3ba0010042d2581cea16653becbc9efa16f
  pid: 9941199_188648413
server:
  port: 80
  tomcat:
    connection-timeout: 60000 #超时时间
    max-connections: 100 #最大连接数，默认为10000
    accept-count: 6 #最大连接等待数，默认100
    threads: #并发数
      max: 100
      min-spare: 5