spring:
  mvc:
    view:
      prefix: classpath:/templates/
      suffix: .html
  logpath: /Users/liuweiran/data/log
  application:
    name: waiter-Sale
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.93.99.85:3306/wechatDB?useUnicode=true&autoReconnect=true&characterEncoding=utf-8
    username: root
    password: liuweiran12138
  profiles:
    active: @spring.profiles.active@
logging:
  config: 'classpath:logback-spring.xml'
  level:
    org.springframework.boot.autoconfigure: ERROR
logback:
  file: ${spring.logpath}/${spring.application.name}
mybatis:
  mapper-locations: classpath:/mapper/*Mapper.xml
  type-aliases-package: xyz.taobaok.wechat.mapper