spring:
  logpath: /Users/liuweiran/data/log
  application:
    name: waiter-Sale
  profiles:
    active: '@spring.profiles.active@'
logging:
  config: 'classpath:logback-spring.xml'
  level:
    org.springframework.boot.autoconfigure: ERROR
logback:
  file: ${spring.logpath}/${spring.application.name}
mybatis:
  mapper-locations: classpath:/mapper/*Mapper.xml
  type-aliases-package: xin.pwdkeeper.wechat.mapper
